### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by frigginglorious** [whackashoe/it#1]
I always thought the --help functions were dynamically generated. I don't know why. This is the first time I've looked at source for a cmd line utility. Will issues automatically be posted here if people are using git?

**Comment by whackashoe** [comment]
Issues wont be posted to github's issue tracker, no. You could maybe write a githook for push to call githubs api and provide a link to the relevant issue.

**Comment by frigginglorious** [comment]
changing the default editor from VIM is of more importance! I wonder what would happen if i uninstalled VIM?

**Comment by whackashoe** [comment]
why would you ever do such a thing?
